#!/usr/bin/env bash

# -----------------------------------------------------------------
# script used to submit the jorek job
# -----------------------------------------------------------------
if [ $# -lt 6 ]; then
   echo "==================================================================================="
   echo " Syntaxe subjorek model_number n_tor n_period n_plane restart_file namelist_file"
   echo "       Example:  subjorek 303 1 1 4 inlowshape.h5 inlowshape"
   echo "==================================================================================="
   echo " "
   exit
fi

# storing the inputs
# ------------------
MODELNUMBER=$1
NTOR=$2
NPERIOD=$3
NPLANE=$4
DATANAME=$5
NMLNAME=$6
echo "==================================================================================="
echo " execution of model '"$MODELNUMBER"' with data file '"$DATANAME"', namelist file '"$NMLNAME"', compiled with "
echo " parameters 'n_tor = "$NTOR"', 'n_period = "$NPERIOD"', 'n_plane = "$NPLANE"'"
echo "==================================================================================="
echo " "

# case name
# ---------
BASEDATANAME=`basename $DATANAME .h5`
CASENAME=`echo $BASEDATANAME | tr '[:lower:]' '[:upper:]'`
MACHNAME=`echo $ARCH | tr '[:lower:]' '[:upper:]'`

FIRSTCAR=${MACHNAME:0:1}
LASTCAR_MODEL=${MODELNUMBER}
CASE=D${FIRSTCAR}_${LASTCAR_MODEL}_${CASENAME}

if [ -f go_$BASEDATANAME.cmd ]; then
   rm -f go_$BASEDATANAME.cmd
fi

# According to ARCH variable
# --------------------------
case ${ARCH} in

# -----------------------------------------------------------------
# norma (IRFM)
# -----------------------------------------------------------------
nfs*)

# batch control
# -------------
MPIPROCS=1
NTHREAD=8
NNODES=2
WALLTIME=02:00:00
((NPES=NNODES*MPIPROCS))
echo "==================================================================================="
echo " ${NNODES} nodes with ${MPIPROCS} process MPI per node and ${NTHREAD} threads per MPI process "
echo " NPES = $NNODES x $MPIPROCS = " $NPES
echo "==================================================================================="
echo " "

# Environment
# -----------
DIR=$(dirname $PWD)
SRCDIR=${SRCDIR:-$DIR}
WKDIR=`pwd`
UTILDIR=${SRCDIR}/util

DIR=${RESPREFIX:-$(basename $(dirname $PWD))}
RESDIR1=/data/${USER}/${DIR}
RESDIR=${RESDIR1}/${CASE}

# Creation of the work directory
# ------------------------------
if [ ! -d ${RESDIR1} ]; then
   mkdir -p ${RESDIR1}
fi

if [ ! -d ${RESDIR} ]; then
   mkdir -p ${RESDIR}
   ln -s ${RESDIR} ${CASE}
fi

source /data/JOREK/jorek_env/jorek_env.sh
;;

# -----------------------------------------------------------------
# ccamu (Marseille)
# -----------------------------------------------------------------
ccamu*)

# batch control
# -------------
MPIPROCS=12
NTHREAD=1
NNODES=16
#NTHREAD=1
#NNODES=1
WALLTIME=00:29:00
((NLIM=MPIPROCS*NTHREAD))
if [ "${NLIM}" -gt "13" ]; then
   echo "${NLIM} = ", ${NLIM}
   echo " MPIPROCS*NTHREAD is greater than 12, you are trying to run more MPI processes and threads than reasonable"
   echo " ===> try running MPIPROCS=1 (1 MPI process per node) and NTHREAD=12 ...."
   exit
fi
((NPES=NNODES*MPIPROCS))
echo "==================================================================================="
echo " ${NNODES} nodes with ${MPIPROCS} process MPI per node and ${NTHREAD} threads per MPI process "
echo " NPES = $NNODES x $MPIPROCS = " $NPES
echo "==================================================================================="
echo " "

# Environment
# -----------
DIR=$(dirname $PWD)
SRCDIR=${SRCDIR:-$DIR}
WKDIR=`pwd`
UTILDIR=${SRCDIR}/util

DIR=${RESPREFIX:-$(basename $(dirname $PWD))}
RESDIR1=/scratch/${USER}/${DIR}
RESDIR1=${RESDIR1%/}
RESDIR=${RESDIR1}/${CASE}

# Creation of the work directory
# ------------------------------
if [ ! -d ${RESDIR1} ]; then
   mkdir -p ${RESDIR1}
fi

if [ ! -d ${RESDIR} ]; then
   mkdir -p ${RESDIR}
   ln -s ${RESDIR} ${CASE}
fi

# Creation of the work directory
# ------------------------------
if [ ! -d ${RESDIR} ]; then
   mkdir -p ${RESDIR}
fi

;;

# -----------------------------------------------------------------
# helios (IFERC)
# -----------------------------------------------------------------
helios*)

# batch control
# -------------
# mpi procs per nodes
MPIPROCS=16
NTHREAD=1
NNODES=4
WALLTIME=24:00:00
((NLIM=MPIPROCS*NTHREAD))
if [ "${NLIM}" -gt "16" ]; then
   echo "${NLIM} = ", ${NLIM}
   echo " MPIPROCS*NTHREAD is greater than 16, you are trying to run more MPI processes and threads than reasonable"
   echo " ===> try running MPIPROCS=1 (1 MPI process per node) and NTHREAD=16 ...."
   exit
fi
((NPES=NNODES*MPIPROCS))
echo "==================================================================================="
echo " ${NNODES} nodes with ${MPIPROCS} process MPI per node and ${NTHREAD} threads per MPI process "
echo " NPES = $NNODES x $MPIPROCS = " $NPES
echo "==================================================================================="
echo " "

# Environment
# -----------
DIR=$(dirname $PWD)
# echo " DIR " $DIR
DIR2=$(dirname $DIR)
# echo " DIR2 " $DIR2
DIR3=$(basename $DIR2)
# echo " DIR3 " $DIR3
HOMEDIR2=$WORKDIR/${DIR}
HOMEDIR=${DIR}
SRCDIR=$HOMEDIR
UTILDIR=${HOMEDIR}/util
WKDIR=`pwd`

RESDIR1=$SCRATCHDIR/${DIR3}
RESDIR=${RESDIR1}/${CASE}
#echo " HOMEDIR " $HOMEDIR
#echo " HOMEDIR2 " $HOMEDIR2
#echo " SRCDIR  " $SRCDIR
#echo " UTILDIR " $UTILDIR
#echo " WKDIR   " $WKDIR
#echo " SCRATCHDIR " $SCRATCHDIR
#echo " RESDIR1    " $RESDIR1
#echo " RESDIR     " $RESDIR


# Creation of the work directory
# ------------------------------
if [ ! -d ${RESDIR1} ]; then
   mkdir -p ${RESDIR1}
fi

if [ ! -d ${RESDIR} ]; then
   mkdir -p ${RESDIR}
   ln -s ${RESDIR} ${CASE}
fi

# Creation of the work directory
# ------------------------------
if [ ! -d ${RESDIR} ]; then
   mkdir -p ${RESDIR}
fi

;;

# -----------------------------------------------------------------
# jade (cines)
# -----------------------------------------------------------------
jade*)

# batch control
# -------------
MPIPROCS=1
NTHREAD=8
NNODES=16
WALLTIME=1800
((NPES=NNODES*MPIPROCS))
echo "==================================================================================="
echo " ${NNODES} nodes with ${MPIPROCS} process MPI per node and ${NTHREAD} threads per MPI process "
echo " NPES = $NNODES x $MPIPROCS = " $NPES
echo "==================================================================================="
echo " "

# Environment
# -----------
DIR=$(basename $(dirname $PWD))
HOMEDIR=/scratch/$USER/${DIR}
SRCDIR=$HOMEDIR
UTILDIR=${SRCDIR}/util

DIR=$(basename $PWD)
WKDIR=${HOMEDIR}/${DIR}
RESDIR1=${WKDIR}
RESDIR=${RESDIR1}/${CASE}

# Creation of the work directory
# ------------------------------
if [ ! -d ${RESDIR} ]; then
   mkdir -p ${RESDIR}
fi
;;

# -----------------------------------------------------------------
# hpc-ff (Juelich)
# -----------------------------------------------------------------
hpcff*)

# batch control
# -------------
NODES=32
NTHREAD=8
PPN=8   # processs per node=8: reserve the whole node
WALLTIME=02:00:00
((NSLOTS=NODES * PPN / NTHREAD))
echo "==================================================================================="
echo " ${NODES} nodes are asked for, with ${PPN} processes per node (the whole node) and ${NTHREAD} threads "
echo "==================================================================================="
echo " "

# Environment
# -----------
DIR=$(dirname $PWD)
SRCDIR=$DIR
WKDIR=`pwd`
UTILDIR=${SRCDIR}/util
RESDIR1=`echo $HOME | sed "s/jhome*[0123456789]/jwork/" `

# Creation of the work directory
# ------------------------------
RESDIR=${RESDIR1}/${CASE}
if [ ! -d ${RESDIR} ]; then
   mkdir -p ${RESDIR}
   ln -s ${RESDIR} ${CASE}
fi
;;

*)
esac


# -----------------------------------------------------------------
# creating the correct executables/verifying they exist
# -----------------------------------------------------------------

# creating the name of the Jorek executable
#------------------------------------------
EXECNAME=JOR${MODELNUMBER}_NTOR${NTOR}_NPER${NPERIOD}_NPLA${NPLANE}.exe
EXECNAMEOUT=${EXECNAME%.*}
VTKEXECNAME=VTK${MODELNUMBER}_NTOR${NTOR}.exe
VTKEXECNAME_REAL=VTKREAL${MODELNUMBER}_NTOR${NTOR}.exe
TARGET_VTKEXECNAME=TARGET_VTK${MODELNUMBER}_NTOR${NTOR}_NPER${NPERIOD}_NPLA${NPLANE}.exe
POWERSEXECNAME=POWERS${MODELNUMBER}_NTOR${NTOR}_NPER${NPERIOD}_NPLA${NPLANE}.exe
STRIKEXECNAME=STRIKES${MODELNUMBER}_NTOR${NTOR}_NPER${NPERIOD}_NPLA${NPLANE}.exe
STRIKEXECNAMEOUT=${STRIKEXECNAME%.*}

if [ ! -e ${SRCDIR}/${STRIKEXECNAME} ]; then
  echo "==================================================================================="
  echo " =============>> model = " $MODELNUMBER", n_tor = " $NTOR", n_period = " $NPERIOD", n_plane = " $NPLANE
  echo " =============>> compiling the jorek2_strikes executable" ${STRIKEXECNAME}
  echo "==================================================================================="
  echo " "
  cd ${SRCDIR}

  ${UTILDIR}/setconfig.sh  model=${MODELNUMBER} n_tor=${NTOR} n_period=${NPERIOD} n_plane=${NPLANE}

  if [ -e jorek2_strikes ]; then rm -f jorek2_strikes; fi
  make cleanall
  # verify that the model in Makefile.inc is set to jorek_model${MODELNUMBER}
  # else, change it in Makefile.inc to jorek_model${MODELNUMBER}
  sed -i "s/  MODEL = .*/  MODEL = model$MODELNUMBER/"  ${SRCDIR}/Makefile.inc
  make jorek2_strikes

  if [ -e jorek2_strikes ]; then mv jorek2_strikes ${STRIKEXECNAME}; fi
fi

#if [ ! -e ${SRCDIR}/${VTKEXECNAME} ]; then
#  echo "==================================================================================="
#  echo " =============>> model = " $MODELNUMBER", n_tor = " $NTOR", n_period = " $NPERIOD", n_plane = " $NPLANE
#  echo " =============>> compiling the jorek2vtk executable" ${VTKEXECNAME}
#  echo "==================================================================================="
#  echo " "
#  cd ${SRCDIR}
#
#  ${UTILDIR}/setconfig.sh  model=${MODELNUMBER} n_tor=${NTOR} n_period=${NPERIOD} n_plane=${NPLANE}
#
#  if [ -e jorek2vtk ]; then rm -f jorek2vtk; fi
#  make cleanall
#  # verify that the model in Makefile.inc is set to jorek_model${MODELNUMBER}
#  # else, change it in Makefile.inc to jorek_model${MODELNUMBER}
#  sed -i "s/  MODEL = .*/  MODEL = model$MODELNUMBER/"  ${SRCDIR}/Makefile.inc
#  make jorek2vtk
#
#  if [ -e jorek2vtk ]; then mv jorek2vtk ${VTKEXECNAME}; fi
#fi
#

#if [ ! -e ${SRCDIR}/${VTKEXECNAME_REAL} ]; then
#  echo "==================================================================================="
#  echo " =============>> model = " $MODELNUMBER", n_tor = " $NTOR", n_period = " $NPERIOD", n_plane = " $NPLANE
#  echo " =============>> compiling the jorek2vtk executable" ${VTKEXECNAME_REAL}
#  echo "==================================================================================="
#  echo " "
#  cd ${SRCDIR}
#
#  ${UTILDIR}/setconfig.sh  model=${MODELNUMBER} n_tor=${NTOR} n_period=${NPERIOD} n_plane=${NPLANE}
#
#  if [ -e jorek2vtk ]; then rm -f jorek2vtk_real; fi
#  make cleanall
#  # verify that the model in Makefile.inc is set to jorek_model${MODELNUMBER}
#  # else, change it in Makefile.inc to jorek_model${MODELNUMBER}
#  sed -i "s/  MODEL = .*/  MODEL = model$MODELNUMBER/"  ${SRCDIR}/Makefile.inc
#  make jorek2vtk_real
#
#  if [ -e jorek2vtk_real ]; then mv jorek2vtk_real ${VTKEXECNAME_REAL}; fi
#fi
#
#if [ ! -e ${SRCDIR}/${TARGET_VTKEXECNAME} ]; then
#  echo "==================================================================================="
#  echo " =============>> model = " $MODELNUMBER", n_tor = " $NTOR", n_period = " $NPERIOD", n_plane = " $NPLANE
#  echo " =============>> compiling the jorek2_target2vtk executable" ${TARGET_VTKEXECNAME}
#  echo "==================================================================================="
#  echo " "
#  cd ${SRCDIR}
#
#  ${UTILDIR}/setconfig.sh  model=${MODELNUMBER} n_tor=${NTOR} n_period=${NPERIOD} n_plane=${NPLANE}
#
#  if [ -e jorek2_target2vtk ]; then rm -f jorek2_target2vtk; fi
##  make cleanall
#  # verify that the model in Makefile.inc is set to jorek_model${MODELNUMBER}
#  # else, change it in Makefile.inc to jorek_model${MODELNUMBER}
#  sed -i "s/  MODEL = .*/  MODEL = model$MODELNUMBER/"  ${SRCDIR}/Makefile.inc
#  make jorek2_target2vtk
#
#  if [ -e jorek2_target2vtk ]; then mv jorek2_target2vtk ${TARGET_VTKEXECNAME}; fi
#fi
#
#if [ ! -e ${SRCDIR}/${POWERSEXECNAME} ]; then
#  echo "==================================================================================="
#  echo " =============>> model = " $MODELNUMBER", n_tor = " $NTOR", n_period = " $NPERIOD", n_plane = " $NPLANE
#  echo " =============>> compiling the jorek2_powers executable" ${POWERSEXECNAME}
#  echo "==================================================================================="
#  echo " "
#  cd ${SRCDIR}
#
#  ${UTILDIR}/setconfig.sh  model=${MODELNUMBER} n_tor=${NTOR} n_period=${NPERIOD} n_plane=${NPLANE}
#
#  if [ -e jorek2_powers ]; then rm -f jorek2_powers; fi
##  make cleanall
#  # verify that the model in Makefile.inc is set to jorek_model${MODELNUMBER}
#  # else, change it in Makefile.inc to jorek_model${MODELNUMBER}
#  sed -i "s/  MODEL = .*/  MODEL = model$MODELNUMBER/"  ${SRCDIR}/Makefile.inc
#  make jorek2_powers
#
#  if [ -e jorek2_powers ]; then mv jorek2_powers ${POWERSEXECNAME}; fi
#fi

cd ${WKDIR}

if [ ! -e ${SRCDIR}/${STRIKEXECNAME} ]; then
   echo "SRCDIR = " ${SRCDIR}
   echo "STRIKEXECNAME = "  ${STRIKEXECNAME}
   echo " Executable ${STRIKEXECNAME} does not exist, so exit ";
   exit
else
    cp ${SRCDIR}/${STRIKEXECNAME} ${RESDIR}/.
fi

if [ ! -e ${WKDIR}/${DATANAME} ]; then
    echo " Datafile ${DATANAME} does no exist, so exit ";
    exit
else
    cp ${WKDIR}/${DATANAME} ${RESDIR}/jorek_restart.h5
fi

if [ ! -e ${WKDIR}/${NMLNAME} ]; then
    echo " namelist file ${NMLNAME} does no exist, so exit ";
    exit
else
    cp ${WKDIR}/${NMLNAME} ${RESDIR}/${NMLNAME}
fi

# parameters for the strike point program (optional)

if [ ! -e ${RESDIR}/connecvtk.nml ]; then
    if [ ! -e ${WKDIR}/connecvtk.nml ]; then
	echo " WARNING: namelist file connecvtk.nml does not exist, will use defaults ";
    else
	cp ${WKDIR}/connecvtk.nml ${RESDIR}/
    fi
else
    echo " using old namelist file connecvtk.nml "
fi

if [ ! -e ${RESDIR}/div_start.dat ]; then
    if [ ! -e ${WKDIR}/div_start.dat ]; then
	echo " ERROR: input file div_start.dat does not exist, exiting ";
	exit 1
    else
	cp ${WKDIR}/div_start.dat ${RESDIR}/
    fi
else
    echo " using old input file div_start.dat "
fi

# Execution control
# -----------------
echo " ============> writing output in file    = " ${CASE}/${STRIKEXECNAMEOUT}.out

# batch job creation
# ------------------
case ${ARCH} in

# -----------------------------------------------------------------
# norma (IRFM)
# -----------------------------------------------------------------
nfs*)

JOREKENV="source /data/JOREK/jorek_env/jorek_env.sh"
CMD_MPIRUN="$JOREKENV; mpirun -np ${NPES} ${RESDIR}/${STRIKEXECNAME} < ${RESDIR}/${NMLNAME} >> ${RESDIR}/${STRIKEXECNAMEOUT}.out"
CMD_SUB="qsub go_${BASEDATANAME}.cmd"
CMD_SUBRST=${CMD_SUB}

# batch job creation
# ------------------
cat <<EOF > go_$BASEDATANAME.cmd
#!/bin/bash
#PBS -N ${CASENAME}
#PBS -V
#PBS -j oe
#PBS -l walltime=${WALLTIME}
#PBS -l select=${NNODES}:ncpus=8:ompthreads=${NTHREAD}:mpiprocs=${MPIPROCS}
## ${NNODES} nodes with ${MPIPROCS} process MPI per node and ${NTHREAD} threads per MPI process

# environment
#------------
ulimit -Sa
ulimit -Ha

# machinefile creation
# -------------------
source /data/JOREK/jorek_env/jorek_env.sh
mpdallexit &> /dev/null
sort -u < \$PBS_NODEFILE > ${RESDIR}/machinefile
mpdboot -n ${NNODES} -f ${RESDIR}/machinefile

EOF
;;

# -----------------------------------------------------------------
# ccamu (Marseille)
# -----------------------------------------------------------------
ccamu*)

CMD_MPIRUN="mpiexec -launcher ssh -launcher-exec oarsh -f ${RESDIR}/mach -iface ib0 -n ${NPES} ${RESDIR}/${STRIKEXECNAME} < ${RESDIR}/${NMLNAME} >> ${RESDIR}/${STRIKEXECNAMEOUT}.out"
CMD_SUB="oarsub -S ./go_${BASEDATANAME}.cmd"
CMD_SUBRST='wrapper_oar "'${CMD_SUB}'"'

# batch job creation
# ------------------
cat <<EOF > go_$BASEDATANAME.cmd
#!/bin/bash
#OAR -n ${CASENAME}
#OAR -l host=${NNODES},walltime=${WALLTIME}
#OAR -p nbcores=12 and visu='NO' 
#OAR -O ${BASEDATANAME}.%jobid%.log
#OAR -E ${BASEDATANAME}.%jobid%.err
##OAR -q development
wrapper_oar() { echo \$1 ; ssh $USER@login "cd ${WKDIR}; \$1 "; }

# environment
#------------
ulimit -Sa
ulimit -Ha

# machinefile creation
# -------------------
echo " == hostfile ==="
cat \$OAR_NODEFILE | sort -u > ${RESDIR}/mach
for i in \$(cat ${RESDIR}/mach); do oarsh \$i hostname; done
cat ${RESDIR}/mach
echo ''

module list

export OMP_NUM_THREADS=${NTHREAD}

EOF
;;

# -----------------------------------------------------------------
# helios (IFERC)
# -----------------------------------------------------------------
helios*)

# Batch control
((MPIPROCS=16/$NTHREAD))
((NCPUS=NPES*NTHREAD))
((NNODES=(NPES*NTHREAD)/16))
if [ $NNODES -eq 0 ]; then
   ((NNODES=1))
fi
echo " NPES " $NPES " NTHREADS " $NTHREAD "MPIPROCS " $MPIPROCS " NNODES " $NNODES

CMD_MPIRUN="mpirun -np ${NPES} ${RESDIR}/${STRIKEXECNAME} < ${RESDIR}/${NMLNAME} >> ${RESDIR}/${STRIKEXECNAMEOUT}.out"   
CMD_SUB="sbatch -A JOREK ./go_${BASEDATANAME}.cmd"
#CMD_SUB="sbatch -A F4E_EU10 ./go_${DATANAME}.cmd"
CMD_SUBRST=${CMD_SUB}

# batch job creation
# ------------------
cat <<EOF > go_$BASEDATANAME.cmd
#!/bin/bash
#SBATCH -J ${CASENAME}              # jobname
#SBATCH -N ${NNODES}              # number of nodes
#SBATCH -n ${NPES}                # number of tasks
#SBATCH -o ${CASENAME}%j.out      # strout filename (%j is jobid)
#SBATCH -e ${CASENAME}%j.out      # stderr filename (%j is jobid)
#SBATCH -t ${WALLTIME}            # execute time (hh:mm:ss - max 08:00:00)
# #SBATCH -A JOREK-0 

# environment
#------------
ulimit -l unlimited

export OMP_NUM_THREADS=${NTHREAD}

EOF
;;

# -----------------------------------------------------------------
# jade (cines)
# -----------------------------------------------------------------
jade*)

CMD_MPIRUN="mpiexec ${RESDIR}/${STRIKEXECNAME} < ${RESDIR}/${NMLNAME} >> ${RESDIR}/${STRIKEXECNAME}.out"
CMD_SUB="qsub go_${BASEDATANAME}.cmd"
CMD_SUBRST=${CMD_SUB}

cat <<EOF > go_$BASEDATANAME.cmd
#!/bin/bash
#PBS -N ${CASENAME}
#PBS -V
#PBS -j oe
#PBS -l walltime=${WALLTIME}
##PBS -l select=${NNODES}:ncpus=8:ompthreads=${NTHREAD}:mpiprocs=${MPIPROCS}
#PBS -l select=1:ncpus=8:ompthreads=${NTHREAD}:mpiprocs=1
## ${NNODES} nodes with ${MPIPROCS} process MPI per node and ${NTHREAD} threads per MPI process

# environment
#------------
ulimit -Sa
ulimit -Ha

export OMP_NUM_THREADS=${NTHREAD}

EOF
;;

# -----------------------------------------------------------------
# hpc-ff (Juelich)
# -----------------------------------------------------------------
hpcff*)

CMD_MPIRUN="mpiexec -np=${NSLOTS} ${RESDIR}/${STRIKEXECNAME} < ${RESDIR}/${NMLNAME} >> ${RESDIR}/${STRIKEXECNAME}.out"
CMD_SUB="msub go_${BASEDATANAME}.cmd"
CMD_SUBRST=${CMD_SUB}

# batch job creation
# ------------------
cat <<EOF > go_$BASEDATANAME.cmd
#!/bin/bash
#MSUB -N ${CASENAME}
# nodes=Nb of nodes, ppn=process per node (max.8)
#MSUB -l nodes=${NODES}:ppn=8
# maximum walltime currently 24hrs walltime=<hh:mm:ss>
#MSUB -l walltime=${WALLTIME}
# tpt = Nb of OmpenMp processes
#MSUB -v tpt=${NTHREAD}
#MSUB -j oe

# for HPC-FF
export OMP_NUM_THREADS=8
export MKL_SERIAL=YES
export KMP_STACKSIZE=256M
export PSI_EXPORTS=MKL_SERIAL,OMP_NUM_THREADS,KMP_STACKSIZE


EOF
;;

*)
esac

cat <<EOF >> go_$BASEDATANAME.cmd
set -vx
cd ${RESDIR}

# run jorek
# ---------
export OMP_NUM_THREADS=${NTHREAD}
${CMD_MPIRUN}

EOF

chmod +x go_$BASEDATANAME.cmd
cd ${WKDIR}
${CMD_SUB}


